apiVersion: v2
name: vc-authentication
description: Umbrella Chart for the FIWARE vc-authentication, combining all essential parts to be used by a participant.
type: application
version: 1.1.4
dependencies:
  - name: vcverifier
    condition: vcverifier.enabled
    version: 4.9.0
    repository: https://fiware.github.io/helm-charts
  - name: credentials-config-service
    condition: credentials-config-service.enabled
    version: 2.5.2
    repository: https://fiware.github.io/helm-charts
  - name: trusted-issuers-list
    condition: trusted-issuers-list.enabled
    version: 0.16.2
    repository: https://fiware.github.io/helm-charts
  - name: dss-validation-service
    alias: dss
    condition: dss.enabled
    version: 0.0.18
    repository: https://fiware.github.io/helm-charts
  - name: postgres-operator
    condition: postgres-operator.enabled
    version: 1.15.1
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
