# did-helper/templates/did-helper-secret.yaml
{{- if .Values.secret.create }}
{{- $existing := lookup "v1" "Secret" $.Release.Namespace .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "did-helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Key: store-pass (referenced in the Deployment initContainer)
  store-pass: |-
    {{- if .Values.secret.storePass }}
    {{ .Values.secret.storePass }}
    {{- else if $existing }}
    {{ index $existing.data "store-pass" }}
    {{- else }}
    {{ randAlphaNum 32 }}
    {{- end }}
{{- end }}