# did-helper/templates/did-helper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: did-helper
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "did-helper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: did-helper
    app.kubernetes.io/instance: {{ .Release.Name }}