global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/keycloak
  tag: 26.3.2-debian-12-r0
postgresql:
  enabled: false
proxyHeaders: xforwarded
proxy: edge
auth:
  existingSecret: keycloak-master-secret
  passwordSecretKey: password
  adminUser: user
containerSecurityContext:
  enabled: false
externalDatabase:
  host: postgres
  database: keycloak
  user: keycloak
  existingSecret: keycloak.postgres.credentials.postgresql.acid.zalan.do
  existingSecretPasswordKey: password
ingress:
  enabled: true
  hostname: keycloak.127.0.0.1.nip.io
  ingressClassName: nginx
resources:
  requests:
    memory: "500Mi"
    cpu: "0.5"
  limits:
    memory: "2Gi"
    cpu: "1"
command:
  - /bin/bash
  - -c
args:
  - |
    #!/bin/sh
    export $(cat /did-material/did.env)
    exec /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh  
initContainers:
  - name: get-did
    image: ubuntu
    command:
      - /bin/bash
    args:
      - -ec
      - |
        #!/bin/bash
        apt-get -y update; apt-get -y install wget; apt-get -y install sed;
        
        cd /did-material
        wget http://did-helper:3001/did-material/cert.pfx
        wget http://did-helper:3001/did-material/did.env
        echo "" >> /did-material/did.env
        echo "CLIENT_DID=did:key:zDnaeweD2CZEV3GArTbbfUtM3PS5LM2QXx1Ahu1KroezYN6qS" >> /did-material/did.env
        echo $(cat /did-material/did.env)
    volumeMounts:
      - name: did-material
        mountPath: /did-material

  - name: prepare-envs
    image: docker.io/bitnamilegacy/keycloak:26.2.1-debian-12-r0
    command:
      - /bin/sh
    args:
      - -ec
      - |
        #!/bin/sh
        export $(cat /etc/env/did.env)
        cp -r /opt/bitnami/scripts/. /env-update/
        echo "export DID=$DID" >> /env-update/keycloak-env.sh
        cat /env-update/keycloak-env.sh
    volumeMounts:
      - name: kc-env
        mountPath: /env-update
      - name: did-material
        mountPath: /etc/env

extraVolumeMounts:
  - name: did-material
    mountPath: /did-material
  - name: did-material
    mountPath: "/etc/env"
    readOnly: true
  - name: realms
    mountPath: /opt/bitnami/keycloak/data/import
  - name: kc-env
    mountPath: /opt/bitnami/scripts/keycloak-env.sh
    subPath: keycloak-env.sh

extraVolumes:
  - name: did-material
    emptyDir: { }
  - name: kc-env
    emptyDir: { }
  - name: realms
    configMap:
      name: test-realm-realm

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: INFO
  - name: KEYCLOAK_HOSTNAME
    value: https://keycloak.127.0.0.1.nip.io:8443
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"
  - name: KC_FEATURES
    value: "oid4vc-vci"
  - name: STORE_PASS
    valueFrom:
      secretKeyRef:
        name: did-helper-secret
        key: store-pass
  - name: KC_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-master-secret
        key: password
  - name: KC_HEAP_SIZE
    value: "1024m"
