apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
spec:    
  teamId: "vc-authentication"
  numberOfInstances: 1
  postgresql:
    version: "16"
  volume:
    size: 1Gi
    storageClass: "local-path"
  users:
    admin: # maintainer
      - superuser
      - createdb
    keycloak:
      - createdb
  databases:
    keycloak: keycloak
  patroni:
    pg_hba: # Allow connections without ssl as db is not exposed
      - local   all all           trust
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret
type: Opaque
data:
  password: dyoyODkmYyRJZEAqTUBiR2F6MXIhSXRGeiVEYkp3cnc=
