repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: fiware
  url: https://fiware.github.io/helm-charts


releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.13.1
  labels:
    deploy: infra
  hooks:
  - events: ["postsync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-f"
      - "./config/coredns.yaml"

- name: keycloak
  namespace: keycloak
  chart: oci://registry-1.docker.io/bitnamicharts/keycloak
  version: 25.2.0
  labels:
    deploy: infra
  needs:
    - vc-authentication/vc-authentication
  values:
    - values/keycloak.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-n"
      - "{{ .Release.Namespace }}"
      - "-f"
      - "./config/keycloak-config.yaml"
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-n"
      - "{{ .Release.Namespace }}"
      - "-f"
      - "./config/did-helper-keystore-pwd.yaml"

- name: did-helper
  namespace: keycloak
  chart: fiware/did-helper
  version: 0.1.8
  labels:
    deploy: infra
  needs:
    - ingress-nginx/ingress-nginx
  values:
    - values/did-helper.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-n"
      - "{{ .Release.Namespace }}"
      - "-f"
      - "./config/did-material-pvc.yaml"

- name: vc-authentication
  namespace: vc-authentication
  chart: ../charts/vc-authentication
  labels:
    deploy: vc-authentication
  needs:
    - ingress-nginx/ingress-nginx
  values:
    - values/vc-authentication.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-n"
      - "{{ .Release.Namespace }}"
      - "-f"
      - "./config/verifier-certs.yaml"
  - events: ["postsync"]
    showlogs: true
    command: "kubectl"
    args:
      - "apply"
      - "-n"
      - "{{ .Release.Namespace }}"
      - "-f"
      - "./config/config-job.yaml"